apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          - name: PGADMIN_DEFAULT_EMAIL
            value: {{ .Values.pgadmin.username }}
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "fullname" . }}
                key: pgadmin-password
          - name: PGADMIN_LISTEN_PORT
            value: "{{ .Values.service.port }}"
          ports:
          - name: {{ .Values.service.name }}
            containerPort: {{.Values.service.port}}
            protocol: TCP         
          volumeMounts:
          - name: pgadmin-data
            mountPath: /var/lib/pgadmin4
          - name: config-volume
            mountPath: /servers/servers.json
            subPath: servers.json
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: pgadmin-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ template "fullname" . }}-server-list
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      tolerations:
      - key: "node-pool"
        operator: "Exists"
        effect: "NoSchedule"