{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
  # kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass }}
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }} 
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ template "fullname" . }}
              port: 
                number: {{ .Values.service.externalPort }}
{{- end }}